[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "torchfoo"
dynamic = ["version"]
dependencies = [
    "torch>= 2.4.0"
]
requires-python = ">=3.10"
authors = [
  {name = "Vinam Arora", email = "vinam@seas.upenn.edu"},
]
description = "A collection of general utilities for PyTorch"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E.*"]


[project.optional-dependencies]
dev = [
    "pytest",
    "black==24.2.0",
]
